from selenium.webdriver.common.by import By

HOMEPAGE_TITLE = (By.ID, 'qa-HOME_TITLE')
NEW_BUTTON = (By.ID, 'qa-CREATE_NOTE')
NEW_NOTE_BUTTON_IN_LEFT = (By.XPATH, '/html/body/div[1]/div/div/div/div/div/div[2]/span/div/ul[1]/li[1]/button')
NEW_NOTE_BUTTON_IN_BODY = (By.ID, 'qa-HOME_WIDGET_CONTROL_Notes_2|0_0|0_I24FY3|13')
OPTIONS_BUTTON_IN_BODY = (By.ID, 'qa-HOME_WIDGET_MENU_Notes_2|0_0|0_I24FY3|13')
NOTE_TITLE = (By.XPATH, '//textarea[@placeholder="Title"]')
NOTE_BODY = (By.ID, 'en-note')
NOTES_BUTTON_IN_LEFT_MENU = (By.ID, 'qa-NAV_ALL_NOTES')
NOTES_BUTTON_IN_BODY = (By.CLASS_NAME, 'eS__h0j9YqpZ7rzWh1Qa')
NOTES_LIST = (By.CLASS_NAME, 'rv-sticky-node-list')
FIRST_NOTE_IN_LIST = (By.XPATH, '//button[@tabindex="0"]')
SECOND_NOTE_IN_LIST = (By.XPATH, '//button[@tabindex="1"]')
HOME_BUTTON = (By.ID, 'qa-NAV_HOME')
MORE_ACTIONS_MENU = (By.XPATH, '//div[@data-tooltipmark="noteactionsdropdown"]')
MORE_ACTIONS_LIST = (By.XPATH, '//ul[@aria-label="Dropdown List"]')
TRASH_BUTTON = (By.CLASS_NAME, '_832s3r8kdOE_SjKO2aq hANwk8g_6_PVeUc1LRQt '
                               'E_lbv7gA85FrFeRroPBY H_L_ZSC9suMHSq9WGzea epNx6nHXkrOz34MJGnzC')
MOVE_TO_TRASH = (By.LINK_TEXT, 'Move to Trash')
MOVED_TO_TRASH_NOTIFICATION = (By.XPATH, '//div[@class="notification notification-success notification-visible"]')
USER_PORTRAIT = (By.ID, 'qa-NAV_USER')
USER_MAIL = (By.CLASS_NAME, 'y6dPdmfxGtP4ugSdRZs7')
IFRAME = (By.ID, 'qa-COMMON_EDITOR_IFRAME')
SORT_OPTIONS = (By.XPATH, '//button[@aria-label="Sort options"]')
SORT_BY_DATE = (By.ID, 'sort_by_date_updated')
